name: "AlphaESS MQTT Bridge"
description: "AlphaESS solar inverter and battery MQTT integration"
version: "0.1.0"
slug: "alphaess_mqtt"
startup: "services"
init: false
ingress: true
ingress_port: 8080

arch:
  - aarch64
  - amd64

map:
  - homeassistant_config:rw

options:
  mqtt_uri: "tcp://core-mosquitto:1883"
  mqtt_user: ""
  mqtt_password: ""
  alphaess_uri: ""

schema:
  mqtt_uri: str
  mqtt_user: str
  mqtt_password: str
  alphaess_uri: str

ports:
  8080/tcp: 8080