name: "Home Assistant MQTT-Bridge"
description: "Home Assistant MQTT-Bridge connect different services to MQTT"
version: "0.1.2"
slug: "home_assistant_mqtt_bridge"
startup: "services"
init: false
ingress: true
ingress_port: 8080

arch:
  - aarch64
  - amd64

map:
  - homeassistant_config:rw

options:
  mqtt_uri: "tcp://core-mosquitto:1883"
  mqtt_user: ""
  mqtt_password: ""
  influx_db_uri: "http://a0d7b954-influxdb:8086"
  influx_db_user: ""
  influx_db_password: ""
  homematic_uri: ""
  homematic_user: ""
  homematic_password: ""

schema:
  mqtt_uri: str
  mqtt_user: str
  mqtt_password: str
  influx_db_uri: str
  influx_db_user: str
  influx_db_password: str
  homematic_uri: str
  homematic_user: str
  homematic_password: str

ports:
  2001/tcp: 2001
  2010/tcp: 2010
